* 2.5 结构编辑
** 快捷键 =M-<RET>= 对应函数  ~(org-meta-return)~

   *功能：* 插入一个新的标题栏，列表项或者行。

   *详细内容：*

   如果当前光标处于一行的开头位置，并且当前位置是一个标题和纯列项的下一行，那么这个命令会在当前当前
   行之前建立一个新的标题和列表（依据上一行是标题还是列表）。当当前位置是处于一个普通的文本行的开头，
   那么这个命令会转换当前行为一个标题。

   如果当前位置处于一个行的中间部份，这个命令会分割当前行，并且使之前的部份保留，之后的部份转换为一
   个新的列表项或者一个新的标题。如果你不想要这个功能，你可以使自定义变量 =org-M-RET-may-split-line=。

   当是一个前缀命令 =C-u= 调用该命令的时候将会无条件的在当前标题的最后一个子树后插入新的标题，保留当
   前内容。如果使用两个前缀 =C-u= ，那么新的标题会在父级标题的最后一个子树创建一个新的标题。


** 快捷键 =C-<RET>= 对应函数 ~(org-insert-heading-respect-content)~

   *功能：* 在当前子树后创建一个新的标题。


** 快捷键 =M-S-<RET>= 对应函数 ~(org-insert-todo-heading)~

   *功能：* 在当前标题后创建一个和当前标题同等级的任务标题（TODO Entry）。查看变量
    =org-treat-insert-todo-heading-as-state-change= 查看更多细节。


** 快捷键 =C-S-<RET>= 对应函数 ~(org-insert-todo-heading-respect-content)~
   
   *功能：* 插入一个与当前标题同等级的任务标题。这个命令与 =C-<RET>= 一样，新标题将会插入到当前标题
    后。


** 快捷键 =<TAB>= 对应函数 ~(org-cycle)~
   
   当这个命令作用在一个没有任何文本的标题的时候会产生以下效果：
   
   1. 第一次 <TAB> 缩减该标题层级为前一个标题的子标题。
   2. 第二次 <TAB> 使该标题的层级增量为前一个标题的父标题，之后每一次增量一个层级直到成为最顶级的标
      题，如果此时再一次触发该命令则回到最初的层级。


** 快捷键 =M-<LEFT>= 对应函数 ~(org-do-promote)~

   提升一个当前标题的层级。

** 快捷键 =M-<RIGHT>= 对应函数 ~(org-do-demote)~

   降低当前标题一个层级。

** 快捷键 =M-S-<LEFT>= 对应函数 ~(org-promote-subtree)~

   提升当前子树一个层级

** 快捷键 =M-S-<RIGHT>= 对应函数 ~(org-demote-subtree)~
   
   降低当前子树一个层级。

** 快捷键 =M-<up>= 对应函数 ~(org-move-subtree-up)~
   
   移动当前子树到上一个同级别的子树之上。

** 快捷键 =M-<down>= 对应函数 ~(org-move-subtree-down)~
   
   移动当前子树到下一个同级别的子树之下。

** 快捷键 =M-h= 对应函数 ~(org-mark-element)~

   高亮标记当前位置的org元素（文本，列表，标题等等）。 如果重复触发该命令将会标记当前org元素之后的
   org元素。 例如： 在一个段落上触发 =M-h= 会高亮标记该段落，如果此时再次触发该命令会高亮标记下一个。


** 快捷键 " C-c @ " 对应函数 ~(org-mark-subtree)~
   
   高亮标记当前子树。 同 =M-h= 一样重复触发这个命令会依此标记之下相同层级的子树。

** 快捷键 =C-c C-x C-w= 对应函数 ~(org-cut-subtree)~

   剪切当前子树。 例如： 把当前子树从丹铅buffer中删除，但是把它保留到剪贴环中，如果触发该命令的同时
   伴随这前缀输入 N （e.g. =C-u N= ）， 那么该命令会按顺序依次删除N个子树。

** 快捷键 =C-c C-x M-w= 对应函数 ~(org-copy-subtree)~

   复制当前子树。 复制当前子树 ，如果触发该命令的同时伴随这前缀输入 N （e.g. =C-u N= ）， 那么该命令
   会按顺序依次复制N个子树。

**  快捷键 =C-c C-x C-y= 对应函数 ~(org-paste-subtree)~

   从剪贴环中复制一个子树到当前位置。 这个操作会为了适应当前标题的层级从而改变子树原先的层级，或者你
   可以通过快捷键前缀 =C-u N= 来设置指定的层级，或者在需要粘贴的位置输入指定级别的标题等级数量的星号
   =*= 后触发该命令。

** 快捷键 =C-y= 对应函数 ~(org-yank)~

   此命令使org内置的粘贴命令。

   依据两个选项的值即 =org-yank-adjusted-subtrees= 和 =org-yank-folded-subtrees=， Org 内置的粘贴命
   令将通过巧妙的方式粘贴子树并且将其折叠起来， 与命令 =C-c C-x C-y= 一样。

   默认情况下， 此命令使不会调整被粘贴的子树的层级的，但是当粘贴子树过长导致之前的内容被抛出在屏幕可
   视范围之外的时候就会自动折叠被粘贴的子树。

   任何伴随前缀命令触发该命令的情况都将会调用emacs本身的粘贴操作，并传递当前前缀命令为命令参数。如果
   要调用普通的粘贴命令最好的方式使通过命令 =C-u C-y=。 如果你在粘贴后使用 ~yank-pop~ 那么它将以原本
   的方式粘贴之前剪贴的内容，当然不会调整它的层级。

** 快捷键 =C-c C-x c= 对应函数 ~(org-clone-subtree-with-time-shift)~ 

   重复复制某个子树到当前位置。 

   你会接收到关于复制几次的提示，而且你可以指定是否改变每条复制的子树中的时间戳。这是很有用的，例如
   如果你需要创建几条关联到几个讲授课程的任务。

   你可以查看该命令的说明获得更详细的内容提示。

** 快捷键 =C-c C-w= 对应函数 ~(org-refile)~

   迁移条目或选区到不同的位置。 请查看 [[file:../9_Cpture--Refile--Archive/9-5_Refile-and-copy.org][Refile and copy]] 获得更加详细的内容提示。

** 快捷键 =C-c ^= 对应函数 ~(org-sort)~

   *排列同样层级的条目。*

   这个命令将会按照一定规则排列在选中区域中的所有条目，相反如果没有选中区域，那么这个命令会按照一定
   规则排列当前条目的子条目。这个命令会在排列前提示你选择何种排列规则，它们有按照字母顺序，按照数值
   大小，按照时间戳顺序（第一个激活的时间戳为优先， 创建时间， 日程预顶时间， 任务截止日期），按照优
   先级，按照TODO关键词顺序（即配置定义时候的顺序）或者按照属性值来排列。同样，反向排列也是可以的。
   你也可以通过使用你自己创建的函数来产生提取排列规则。如果该命令触发于前缀 =C-u= 后，排序执行会是大
   小写敏感的。


** 快捷键 =C-x n s= 对应函数 ~(org-narrow-to-subtree)~
   
   缩减当前buffer的可视和编辑范围到当前子树。

** 快捷键 =C-x n b= 对应函数 ~(org-narrow-to-block)~

   缩减当前buffer的可视和编辑范围到当前区块。

** 快捷键 =C-x n w= 对应函数 ~(widen)~

   展开缩减区域。

** 快捷键 =C-c *= 对应函数 ~(org-toggle-heading)~

   把普通的行或者纯列表转换到标题（隶属于当前位置的标题之下）。 同样也可以转换一个标题到普通的行（也
   就是删除 =*= ）。如果执行该命令的时候，当前buffer有选中区域， 那么转换所有选中的普通行到标题。如
   果区域中的第一个行是一个列表项目，只把标题项转换到标题，最后如果第一行是标题那么把区域中所有的标
   题转换到普通行。


** 提示 

   如果在选中区域中执行这些命令（Tansient Mark mode）， 提示和降级操作将会作用在区域中所有的标题。要
   选中一个区域中的标题，最好的方式是把光标和标记放置在一行的开头，把标记放置在区域中第一个标题的开
   头，然后光标放置在最后一个标题的下一行。 注意如果光标在一个表格中（参阅 [[file:../3_Tables/3_Tables.org][表格]]） Meta-Cursor键有不
   同的功能。


* COMMENT 原文
  #+BEGIN_EXAMPLE
    File: org.info,  Node: Structure editing,  Next: Sparse trees,  Prev: Motion,  Up: Document structure

    2.5 Structure editing
    =====================

    ‘M-<RET>’     (‘org-meta-return’)
         Insert a new heading, item or row.

         If the command is used at the _beginning_ of a line, and if there
         is a heading or a plain list item (*note Plain lists::) at point,
         the new heading/item is created _before_ the current line.  When
         used at the beginning of a regular line of text, turn that line
         into a heading.

         When this command is used in the middle of a line, the line is
         split and the rest of the line becomes the new item or headline.
         If you do not want the line to be split, customize
         ‘org-M-RET-may-split-line’.

         Calling the command with a ‘C-u’ prefix unconditionally inserts a
         new heading at the end of the current subtree, thus preserving its
         contents.  With a double ‘C-u C-u’ prefix, the new heading is
         created at the end of the parent subtree instead.
    ‘C-<RET>’     (‘org-insert-heading-respect-content’)
         Insert a new heading at the end of the current subtree.
    ‘M-S-<RET>’     (‘org-insert-todo-heading’)
         Insert new TODO entry with same level as current heading.  See also
         the variable ‘org-treat-insert-todo-heading-as-state-change’.
    ‘C-S-<RET>’     (‘org-insert-todo-heading-respect-content’)
         Insert new TODO entry with same level as current heading.  Like
         ‘C-<RET>’, the new headline will be inserted after the current
         subtree.
    ‘<TAB>’     (‘org-cycle’)
         In a new entry with no text yet, the first <TAB> demotes the entry
         to become a child of the previous one.  The next <TAB> makes it a
         parent, and so on, all the way to top level.  Yet another <TAB>,
         and you are back to the initial level.
    ‘M-<LEFT>’     (‘org-do-promote’)
         Promote current heading by one level.
    ‘M-<RIGHT>’     (‘org-do-demote’)
         Demote current heading by one level.
    ‘M-S-<LEFT>’     (‘org-promote-subtree’)
         Promote the current subtree by one level.
    ‘M-S-<RIGHT>’     (‘org-demote-subtree’)
         Demote the current subtree by one level.
    ‘M-<UP>’     (‘org-move-subtree-up’)
         Move subtree up (swap with previous subtree of same level).
    ‘M-<DOWN>’     (‘org-move-subtree-down’)
         Move subtree down (swap with next subtree of same level).
    ‘M-h’     (‘org-mark-element’)
         Mark the element at point.  Hitting repeatedly will mark subsequent
         elements of the one just marked.  E.g., hitting ‘M-h’ on a
         paragraph will mark it, hitting ‘M-h’ immediately again will mark
         the next one.
    ‘C-c @’     (‘org-mark-subtree’)
         Mark the subtree at point.  Hitting repeatedly will mark subsequent
         subtrees of the same level than the marked subtree.
    ‘C-c C-x C-w’     (‘org-cut-subtree’)
         Kill subtree, i.e., remove it from buffer but save in kill ring.
         With a numeric prefix argument N, kill N sequential subtrees.
    ‘C-c C-x M-w’     (‘org-copy-subtree’)
         Copy subtree to kill ring.  With a numeric prefix argument N, copy
         the N sequential subtrees.
    ‘C-c C-x C-y’     (‘org-paste-subtree’)
         Yank subtree from kill ring.  This does modify the level of the
         subtree to make sure the tree fits in nicely at the yank position.
         The yank level can also be specified with a numeric prefix
         argument, or by yanking after a headline marker like ‘****’.
    ‘C-y’     (‘org-yank’)
         Depending on the options ‘org-yank-adjusted-subtrees’ and
         ‘org-yank-folded-subtrees’, Org’s internal ‘yank’ command will
         paste subtrees folded and in a clever way, using the same command
         as ‘C-c C-x C-y’.  With the default settings, no level adjustment
         will take place, but the yanked tree will be folded unless doing so
         would swallow text previously visible.  Any prefix argument to this
         command will force a normal ‘yank’ to be executed, with the prefix
         passed along.  A good way to force a normal yank is ‘C-u C-y’.  If
         you use ‘yank-pop’ after a yank, it will yank previous kill items
         plainly, without adjustment and folding.
    ‘C-c C-x c’     (‘org-clone-subtree-with-time-shift’)
         Clone a subtree by making a number of sibling copies of it.  You
         will be prompted for the number of copies to make, and you can also
         specify if any timestamps in the entry should be shifted.  This can
         be useful, for example, to create a number of tasks related to a
         series of lectures to prepare.  For more details, see the docstring
         of the command ‘org-clone-subtree-with-time-shift’.
    ‘C-c C-w’     (‘org-refile’)
         Refile entry or region to a different location.  *Note Refile and
         copy::.
    ‘C-c ^’     (‘org-sort’)
         Sort same-level entries.  When there is an active region, all
         entries in the region will be sorted.  Otherwise the children of
         the current headline are sorted.  The command prompts for the
         sorting method, which can be alphabetically, numerically, by time
         (first timestamp with active preferred, creation time, scheduled
         time, deadline time), by priority, by TODO keyword (in the sequence
         the keywords have been defined in the setup) or by the value of a
         property.  Reverse sorting is possible as well.  You can also
         supply your own function to extract the sorting key.  With a ‘C-u’
         prefix, sorting will be case-sensitive.
    ‘C-x n s’     (‘org-narrow-to-subtree’)
         Narrow buffer to current subtree.
    ‘C-x n b’     (‘org-narrow-to-block’)
         Narrow buffer to current block.
    ‘C-x n w’     (‘widen’)
         Widen buffer to remove narrowing.
    ‘C-c *’     (‘org-toggle-heading’)
         Turn a normal line or plain list item into a headline (so that it
         becomes a subheading at its location).  Also turn a headline into a
         normal line by removing the stars.  If there is an active region,
         turn all lines in the region into headlines.  If the first line in
         the region was an item, turn only the item lines into headlines.
         Finally, if the first line is a headline, remove the stars from all
         headlines in the region.

       When there is an active region (Transient Mark mode), promotion and
    demotion work on all headlines in the region.  To select a region of
    headlines, it is best to place both point and mark at the beginning of a
    line, mark at the beginning of the first headline, and point at the line
    just after the last headline to change.  Note that when the cursor is
    inside a table (*note Tables::), the Meta-Cursor keys have different
    functionality.
  #+END_EXAMPLE

