* 安装 Installation
  Org是最近几个GNU Emacs发行版本的一部分，所以你在正常情况下是不需要安装它的。如果未来某些理由你想
  要安装最新的预发行版本的Org，这里有三种方法去实行：
    
  - 通过使用Emacs的包管理系统。
  - 通过下载Org的包作为存档。
  - 通过使用Org的git仓库。

      
  我们强烈的建议坚持只用一种安装方式。

  #+BEGIN_SRC org
    Org is part of recent distributions of GNU Emacs, so you normally don't need to install it. If, for
    one reason or another , you want to install Org on top of this pre-package version, there are three
    ways to do it:

    - By using Emacs package system.
    - By downloading Org as an archive.
    - By usin Org's git repository.


    We strongly recommend to stick to a single installation method.
  #+END_SRC

  *使用Emacs包管理系统*

  最近几个Emacs发行版包含了一个包管理系统，它让你安装Elisp的库。你可以使用 ~M-x package-install
  RET org~ 来安装Org.

  重要的事： 你需要在没有 =.org= 文件被打开的情况下做这件事情，即：没有Org内置的函数被加载的情况。
  另一方面 =autoload= Org 函数将搞乱整个安装过程。

  然后，确定你的Org配置文件内容是被充分考量的，在设置Org选项之前在你的 ~.emacs~ 配置文件中使用
  =(package-initialize)= 初始化包管理系统。如果你想要使用Org的包仓库，请检查 =Org ELPA= 页面
  （http://orgmode.org/elpa.html）。

  #+BEGIN_SRC org
    *Using Emacs packaging system*

    Recent Emacs distributions include a packageing system which lets you install Elisp
    libraries. You can install Org with ~M-x package-install RET org~ .

    Important: you need to do this in a session where no '.org' file has been visited, i.e., where
    no Org built-in function have been loaded. Otherwise autoload Org functions will mess up the
    installation.

    Then, to make sure your Org configuration is take into account, innitialize the package system
    with ~(package-initialize)~ in your '.emacs' before setting any Org option. If you want to use
    Org's package repository, check out the Org Elpa page(http://orgmode.org/elpa.html).
  #+END_SRC
    
  *下载Org作为存档*

  你能从Org的网站(http://orgmode.org)下载到最新版本Org。在这种情况下，请确定你在你的'.emacs'中正确
  设置了加载路径：
  #+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/path/to/orgdir/contrib/lisp/" t)
  #+END_SRC

  可选择地，你能编译后者安装它们到你的系统中。运行 ‘make help’ 列出编译和安装选项。
    
  使用Org的git仓库
  ................

  你可以像这样克隆Org的仓库和安装Org：
  #+BEGIN_SRC bash
    $ cd ~/src/
    $ git clone git://orgmode.org/org-mode.git
    $ make autoloads
  #+END_SRC

  记住在这种情况下， 'make autoloads' 是强制的：它在 `org-version.el' 和 `org-loaddefs.el' 中分别
  定义了Org的版本和Org的 =autoloads= (自动加载配置)。
   
  记住要像以上的方法描述的一样正确的加载路径。

  你但你果然也可以使用 ~make~ 命令编译Org,使用 ~make doc~ 生成文档，使用 ~make config~ 创建配置文
  件，和使用 ~make install~ 安装Org到系统。 请运行 ~make config~ 获取编译和安装选项列表。

  更多的关于Org的体系，请查阅 Org 体系网页： (http://orgmode.org/worg/dev/org-build-system.html)。

  #+BEGIN_SRC org
    ,*Downloading Org as an archive*

    You can download Org lateast release form Org's website (http://orgmode.org). In this case, make
    sure you set the load-path correctly in your '.emacs':

    ,#+BEGIN_SRC emacs-lisp
    (add-to-list 'load-path "~/path/to/orgdir/contrib/listp" t)
    ,#+END_SRC

    Optionally, you can compile the files and/or install them in your system. Run `make help` to list
    compilation and installation options.

    Using Org's git repository
    ..........................

    You can clone Org's repository and install Org like this:

    ,#+BEGIN_SRC bash
    $ cd ~/src/
    $ git clone git://orgmode.org/org-mode.git
    $ make autoloads
    ,#+END_SRC

    Note that in this case, 'make autoloads' is mandatory: it defines Org's version in 'org-version.el'
    and Org's autoloads in 'org-loaddefs.el'


    Remamber to add the correct load-path as describe in method above.

    You can also compile with 'make', generatte the documentation with 'make doc'; create a local
    configuration with ' make config' and install Org with 'make install'. Please run 'make help' to get
    the list of comilation/installation options.

    Fr more detailed explanations on Org's build system, please check the Org Build System page on Worg
    (http://orgmode.org/worg/dev/org-build-system.html).
  #+END_SRC
